services:

  db:
    image: postgres
    container_name: bot-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: bot
    volumes:
      - ./pg-data:/var/lib/postgresql/data

networks:
  bot-network:
    driver: bridge